CREATE TABLE USERS
(
U_ID numeric(9) IDENTITY,
U_LOGIN VARCHAR(40) DEFAULT ' ' NOT NULL,
U_NAME VARCHAR(40) DEFAULT ' ' NOT NULL,
U_PASSWORD VARCHAR(40) DEFAULT ' ' NOT NULL,
U_LAST_LOGIN DATETIME DEFAULT GETDATE() NOT NULL,
U_VALIDITY DATETIME DEFAULT GETDATE()-1 NOT NULL,
U_MAIL VARCHAR(40) DEFAULT ' ' NOT NULL,
U_ADDRESS_LINE1 VARCHAR(100) DEFAULT ' ' NOT NULL,
U_ADDRESS_LINE2 VARCHAR(100) DEFAULT ' ' NOT NULL,
U_PHONE VARCHAR(20) DEFAULT ' ' NOT NULL,
U_COUNTRY VARCHAR(40) DEFAULT ' ' NOT NULL,
U_STATE VARCHAR(40) DEFAULT ' ' NOT NULL,
U_SPL_NAME VARCHAR(100) DEFAULT ' ' NOT NULL,
U_ACTIVE   NUMERIC(2) DEFAULT 0 NOT NULL,
UNIQUE (U_LOGIN),
PRIMARY KEY(U_ID)
)
CREATE  TABLE ORGANISATION
(
ORG_ID numeric(9) IDENTITY,
ORG_NAME VARCHAR(100) DEFAULT ' ' NOT NULL,
ORG_ENAME VARCHAR(100) DEFAULT ' ' NOT NULL,
ORG_ADDRESS_LINE1 VARCHAR(100) DEFAULT ' ' NOT NULL,
ORG_ADDRESS_LINE2 VARCHAR(100) DEFAULT ' ' NOT NULL,
ORG_PHONE VARCHAR(20) DEFAULT ' ' NOT NULL,
ORG_COUNTRY VARCHAR(40) DEFAULT ' ' NOT NULL,
ORG_STATE VARCHAR(40) DEFAULT ' ' NOT NULL,
ORG_SPL_NAME VARCHAR(100) DEFAULT ' ' NOT NULL,
PRIMARY KEY(ORG_ID)
)

CREATE TABLE ORG_MODULE
(
M_ID numeric(9) IDENTITY,
M_NAME VARCHAR(40) DEFAULT ' ' NOT NULL,
M_NAME_SPL VARCHAR(40) DEFAULT ' ' NOT NULL,
PRIMARY KEY(M_ID)
)

CREATE TABLE ORG_DATABASE
(
D_ID numeric(9) IDENTITY,
D_TYPE NUMERIC(2) DEFAULT 0 NOT NULL,
D_SOURCE VARCHAR(40) DEFAULT ' ' NOT NULL,
D_DATABASE_NAME  VARCHAR(40) DEFAULT ' ' NOT NULL,
D_USER VARCHAR(40) DEFAULT ' ' NOT NULL,
D_PASS VARCHAR(40) DEFAULT ' ' NOT NULL,
D_ACTIVE NUMERIC(2) DEFAULT 0 NOT NULL,
D_VALIDITY DATETIME DEFAULT GETDATE()+180 NOT NULL,
PRIMARY KEY(D_ID)
)

CREATE TABLE MENUS
(
MENU_ID NUMERIC(9) IDENTITY,
MENU_NAME VARCHAR(40) DEFAULT ' ' NOT NULL,
MENU_ACTION VARCHAR(40) DEFAULT ' ' NOT NULL,
MENU_PARENT_ID NUMERIC(9) DEFAULT 0 NOT NULL,
MENU_ACTIVE NUMERIC(2) DEFAULT 0 NOT NULL,
PRIMARY KEY(MENU_ID)
)

CREATE TABLE PROFILE
(
P_ID NUMERIC(9) IDENTITY,
P_NAME VARCHAR(40) DEFAULT ' ' NOT NULL,
PRIMARY KEY(P_ID)
)

CREATE TABLE ORG_MODULE_DB
(
OMD_ID numeric(9) IDENTITY,
OMD_ORG_ID numeric(9) DEFAULT 0 NOT NULL ,
OMD_MODULE_ID numeric(9) DEFAULT 0 NOT NULL,
OMD_DB_ID numeric(9) DEFAULT 0 NOT NULL,
PRIMARY KEY(OMD_ID),
UNIQUE (OMD_ORG_ID,OMD_MODULE_ID,OMD_DB_ID)
)

CREATE TABLE ORG_PROFILE
(
OP_ID numeric(9) IDENTITY,
OP_OMD_ID numeric(9) DEFAULT 0 NOT NULL ,
OP_PROFILE_ID numeric(9) DEFAULT 0 NOT NULL,
PRIMARY KEY(OP_ID),
UNIQUE (OP_OMD_ID,OP_PROFILE_ID)
)


CREATE TABLE PROFILE_RIGHTS
(
PR_ID NUMERIC(9) IDENTITY,
PR_MENU_ID NUMERIC(9) DEFAULT 0 NOT NULL,
PR_PROF_ID NUMERIC(9) DEFAULT 0 NOT NULL,
PR_CREATE NUMERIC(2) DEFAULT 0 NOT NULL,
PR_READ NUMERIC(2) DEFAULT 0 NOT NULL,
PR_UPDATE NUMERIC(2) DEFAULT 0 NOT NULL,
PR_DELETE NUMERIC(2) DEFAULT 0 NOT NULL,
PRIMARY KEY(PR_ID),
UNIQUE (PR_MENU_ID,PR_PROF_ID)
)

CREATE TABLE MODULE_MENU
(
MM_ID numeric(9) IDENTITY,
MM_MENU_ID numeric(9) DEFAULT 0 NOT NULL ,
MM_MODULE_ID numeric(9) DEFAULT 0 NOT NULL,
PRIMARY KEY(MM_ID),
UNIQUE (MM_MENU_ID,MM_MODULE_ID)
)


CREATE TABLE USER_PROFILE(
UP_ID numeric(9) IDENTITY,
UP_USER_ID numeric(9) DEFAULT 0 NOT NULL ,
UP_PROF_ID numeric(9) DEFAULT 0 NOT NULL,
PRIMARY KEY(UP_ID),
UNIQUE (UP_USER_ID,UP_PROF_ID)
)

CREATE TABLE USER_RIGHTS(
UR_ID numeric(9) IDENTITY,
UR_USER_ID numeric(9) DEFAULT 0 NOT NULL ,
UR_MENU_ID NUMERIC(9) DEFAULT 0 NOT NULL,
UR_CREATE NUMERIC(2) DEFAULT 0 NOT NULL,
UR_READ NUMERIC(2) DEFAULT 0 NOT NULL,
UR_UPDATE NUMERIC(2) DEFAULT 0 NOT NULL,
UR_DELETE NUMERIC(2) DEFAULT 0 NOT NULL,
PRIMARY KEY(UR_ID),
UNIQUE (UR_MENU_ID,UR_USER_ID)
)




